project:
  type: book

book:
  title: "mysite"
  author: "Jane Doe"
  date: "11/19/2021"
  chapters:
    - index.qmd
    - a_page.qmd

filters:
  - quarto
  - noteout-write-doc

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
